name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Dotnet Build
    runs-on: windows-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.17
      - name: Restore Dependencies
        run: dotnet restore
      - name: Run Tests
        run: dotnet test --no-build
