name: .NET Core Desktop

on:
  push:
    branches:
      - main

jobs:
  buil_and_test:
    runs-on: windows-latest
    
    steps:
      - name: Get code from repo
        uses: actions/checkout@v4

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.17

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build
